In [81]:
import pandas as pd
df = pd.read_csv('c:/py_data/py_project/코로나 이전 집콕.csv', encoding='cp949')
del df['Unnamed: 0']
df

       단어   횟수
0      생각  380
1      엄마  342
2      카페  302
3      바로  260
4     드라마  240
...   ...  ...
9796   리노    2
9797   납부    2
9798  개월치    2
9799   금액    2
9800   통큰    2

[9801 rows x 2 columns]

In [82]:
df_1 = pd.read_csv('c:/py_data/py_project/구글 뉴스-코로나 이전 집콕.csv', encoding='cp949')
del df_1['Unnamed: 0']

In [83]:
df_1

       단어   횟수
0      주행  322
1       정  310
2     드라마   81
3       일   68
4      자율   57
...   ...  ...
2109    상    1
2110    데    1
2111  김어준    1
2112   공장    1
2113   짤짤    1

[2114 rows x 2 columns]

In [84]:
df_2 = pd.read_csv('c:/py_data/py_project/네이버카페-코로나 이전 집콕 정주행.csv', encoding='cp949')
del df_2['Unnamed: 0']
df_2

       단어   횟수
0       저  317
1       집  159
2     드라마  142
3      주행  139
4       정  137
...   ...  ...
3456   폐해    1
3457   로선    1
3458   입추    1
3459   누진    1
3460   고해    1

[3461 rows x 2 columns]

In [85]:
df_before = pd.concat([df,df_1,df_2])
df_before

       단어   횟수
0      생각  380
1      엄마  342
2      카페  302
3      바로  260
4     드라마  240
...   ...  ...
3456   폐해    1
3457   로선    1
3458   입추    1
3459   누진    1
3460   고해    1

[15376 rows x 2 columns]

In [86]:
df_before = pd.pivot_table(df_before,
                          index = ['단어'],
                          aggfunc = sum)
df_before

     횟수
단어
가가    5
가게   24
가격   55
가경동   2
가계    2
..   ..
힙하    2
힙합    3
힛     1
힝     1
힝굴    2

[12234 rows x 1 columns]

In [87]:
df_before.sort_values(by=['횟수'],ascending = False, inplace=True)
df_before

        횟수
단어
주행     531
드라마    463
정      447
생각     432
엄마     365
...    ...
자유시간     1
킬        1
킨텍스      1
두목       1
스트레이트    1

[12234 rows x 1 columns]

In [88]:
df_before.drop(df_before.index[4], inplace=True)
df_before

        횟수
단어
주행     531
드라마    463
정      447
생각     432
카페     335
...    ...
자유시간     1
킬        1
킨텍스      1
두목       1
스트레이트    1

[12233 rows x 1 columns]

In [89]:
df_before.reset_index(drop=False, inplace=True)
df_before

          단어   횟수
0         주행  531
1        드라마  463
2          정  447
3         생각  432
4         카페  335
...      ...  ...
12228   자유시간    1
12229      킬    1
12230    킨텍스    1
12231     두목    1
12232  스트레이트    1

[12233 rows x 2 columns]

In [76]:
df_before.to_csv('c:/py_data/py_project/Before 코로나 단어집계(집콕정주행).csv', encoding='cp949')

In [90]:
df_before

          단어   횟수
0         주행  531
1        드라마  463
2          정  447
3         생각  432
4         카페  335
...      ...  ...
12228   자유시간    1
12229      킬    1
12230    킨텍스    1
12231     두목    1
12232  스트레이트    1

[12233 rows x 2 columns]

In [91]:
before_cloud = df_before.to_dict()
before_cloud

{'단어': {0: '주행',
  1: '드라마',
  2: '정',
  3: '생각',
  4: '카페',
  5: '저',
  6: '영화',
  7: '바로',
  8: '저녁',
  9: '영상',
  10: '아침',
  11: '정주',
  12: '주말',
  13: '추천',
  14: '오빠',
  15: '친구',
  16: '일상',
  17: '마음',
  18: '언니',
  19: '남편',
  20: '아빠',
  21: '선물',
  22: '사랑',
  23: '사실',
  24: '복사',
  25: '도움말',
  26: '이상',
  27: '다음',
  28: '커피',
  29: '행복',
  30: '집',
  31: '노래',
  32: '점심',
  33: '맥주',
  34: '이야기',
  35: '아직',
  36: '가지',
  37: '주문',
  38: '맛집',
  39: '느낌',
  40: '연휴',
  41: '기분',
  42: '시즌',
  43: '아기',
  44: '오늘',
  45: '퇴근',
  46: '전',
  47: '혼자',
  48: '병원',
  49: '치킨',
  50: '집콕',
  51: '화질',
  52: '일',
  53: '출근',
  54: '보기',
  55: '최고',
  56: '여행',
  57: '트랙',
  58: '거리',
  59: '아이',
  60: '넷플릭스',
  61: '기도',
  62: '선택',
  63: '시간',
  64: '다리',
  65: '날씨',
  66: '위해',
  67: '먹기',
  68: '소스',
  69: '언제',
  70: '블로그',
  71: '포스팅',
  72: '블랙',
  73: '월요일',
  74: '동안',
  75: '웹툰',
  76: '부산',
  77: '하늘',
  78: '준비',
  79: '종일',
  80: '음식',
  81: '것',
  82: '구경',
  83: '배우',
  84: '원래',
  85: '갑자기',
  86: '서울',
  87: '여름',
  88: '지나',
  89: '가족',
  90: '일요일',
  91: '마무리',
  92: '운동',
  93: '먹음',
  94: '고민',
  95: '한국',
  96: '수',
  97: '그녀',
  98: '인생',
  99: '세상',
  100: '때',
  101: '데이',
  102: '회사',
  103: '메뉴',
  104: '근처',
  105: '보이',
  106: '보고',
  107: '벌써',
  108: '재미',
  109: '티비',
  110: '일찍',
  111: '도착',
  112: '아가',
  113: '재생',
  114: '고기',
  115: '일단',
  116: '더',
  117: '바람',
  118: '토요일',
  119: '여운',
  120: '방송',
  121: '기억',
  122: '던데',
  123: '가야',
  124: '의사',
  125: '미세먼지',
  126: '길이',
  127: '이건',
  128: '모습',
  129: '기능',
  130: '이유',
  131: '내일',
  132: '드디어',
  133: '금요일',
  134: '뭔가',
  135: '장님',
  136: '이벤트',
  137: '시리즈',
  138: '자주',
  139: '다행',
  140: '크리스마스',
  141: '태풍',
  142: '예약',
  143: '나노',
  144: '분위기',
  145: '드론',
  146: '여서',
  147: '동네',
  148: '일어',
  149: '동영상',
  150: '이름',
  151: '하루',
  152: '모두',
  153: '치즈',
  154: '추석',
  155: '얼굴',
  156: '안내',
  157: '관련',
  158: '덕분',
  159: '고요',
  160: '과자',
  161: '좀',
  162: '요',
  163: '존맛',
  164: '꿀떡',
  165: '출연',
  166: '주소',
  167: '포장',
  168: '내내',
  169: '사이',
  170: '수업',
  171: '고마',
  172: '예전',
  173: '떡볶이',
  174: '돼지',
  175: '침대',
  176: '거나',
  177: '피자',
  178: '놀이',
  179: '마우스',
  180: '캐슬',
  181: '화면',
  182: '안녕',
  183: '옵션',
  184: '발견',
  185: '간식',
  186: '아들',
  187: '사용',
  188: '나름',
  189: '약속',
  190: '케이크',
  191: '스카이',
  192: '가을',
  193: '동생',
  194: '눈물',
  195: '라면',
  196: '겨울',
  197: '정리',
  198: '유니',
  199: '오후',
  200: '기초',
  201: '매일',
  202: '내용',
  203: '플레이어',
  204: '파서',
  205: '얼른',
  206: '회',
  207: '공부',
  208: '외출',
  209: '인코딩',
  210: '멀티',
  211: '라이센스',
  212: '우측',
  213: '음소거',
  214: '마트',
  215: '공유소스',
  216: '배달',
  217: '선거',
  218: '레이어',
  219: '래그',
  220: '산책',
  221: '예정',
  222: '디자인',
  223: '아야',
  224: '만족',
  225: '파티',
  226: '광고정보',
  227: '지금',
  228: '여주',
  229: '낮잠',
  230: '일주일',
  231: '생일',
  232: '걱정',
  233: '구들',
  234: '미리',
  235: '파스타',
  236: '지고',
  237: '자꾸',
  238: '이불',
  239: '안나',
  240: '환자',
  241: '가장',
  242: '세트',
  243: '자율',
  244: '고생',
  245: '여유',
  246: '구매',
  247: '진짜',
  248: '해도',
  249: '스토리',
  250: '스타일',
  251: '올해',
  252: '이사',
  253: '가격',
  254: '건강',
  255: '인기',
  256: '가면',
  257: '거',
  258: '생활',
  259: '다리미',
  260: '공연',
  261: '학교',
  262: '항상',
  263: '이',
  264: '바다',
  265: '비행기',
  266: '간만',
  267: '와중',
  268: '수다',
  269: '요즘',
  270: '반찬',
  271: '제품',
  272: '먼저',
  273: '가능',
  274: '년',
  275: '추억',
  276: '작품',
  277: '나니',
  278: '명절',
  279: '버스',
  280: '이모',
  281: '무료',
  282: '신랑',
  283: '하자',
  284: '공감',
  285: '무조건',
  286: '간다',
  287: '캐릭터',
  288: '남자',
  289: '새벽',
  290: '주인공',
  291: '휴가',
  292: '디저트',
  293: '컬러',
  294: '추가',
  295: '아이스',
  296: '방문',
  297: '해먹',
  298: '콩나물',
  299: '떡뻥',
  300: '요한',
  301: '토리',
  302: '인스타',
  303: '번',
  304: '타임',
  305: '얼마',
  306: '박스',
  307: '나중',
  308: '자기',
  309: '진행',
  310: '리지',
  311: '개봉',
  312: '미러',
  313: '저희',
  314: '이번',
  315: '취향',
  316: '뭐',
  317: '과일',
  318: '동백꽃',
  319: '소개',
  320: '공기',
  321: '그릇',
  322: '안보',
  323: '사서',
  324: '공기청정기',
  325: '은지',
  326: '시원',
  327: '주신',
  328: '뷰티',
  329: '야채',
  330: '당근',
  331: '소리',
  332: '유튜브',
  333: '얼마나',
  334: '해',
  335: '얘기',
  336: '쇼핑',
  337: '무지',
  338: '양념',
  339: '동시',
  340: '오전',
  341: '다시',
  342: '아마',
  343: '냄새',
  344: '혹시',
  345: '또',
  346: '맘',
  347: '갈비',
  348: '김치',
  349: '볶음밥',
  350: '작가',
  351: '대로',
  352: '아해',
  353: '필터',
  354: '살짝',
  355: '롯데',
  356: '오기',
  357: '기대',
  358: '전부',
  359: '잠깐',
  360: '게임',
  361: '심심',
  362: '연기',
  363: '로맨스',
  364: '대기',
  365: '아이스크림',
  366: '수가',
  367: '이후',
  368: '제대로',
  369: '그림',
  370: '요리',
  371: '오래',
  372: '평소',
  373: '관심',
  374: '유명',
  375: '화요일',
  376: '멜로',
  377: '통증',
  378: '일본',
  379: '볶음',
  380: '순이',
  381: '이유식',
  382: '사람',
  383: '관람',
  384: '감독',
  385: '그냥',
  386: '행사',
  387: '우린',
  388: '세계',
  389: '여러',
  390: '며칠',
  391: '수요일',
  392: '영어',
  393: '우리',
  394: '제',
  395: '이제',
  396: '정신',
  397: '라떼',
  398: '한번',
  399: '무엇',
  400: '중인',
  401: '온천천',
  402: '마치',
  403: '간단',
  404: '여러분',
  405: '월',
  406: '날',
  407: '혜림이',
  408: '정말',
  409: '었다',
  410: '제거',
  411: '카레',
  412: '애',
  413: '검사',
  414: '사이즈',
  415: '꾹꾹',
  416: '성공',
  417: '리기',
  418: '매력',
  419: '이케아',
  420: '미용실',
  421: '전화',
  422: '패션',
  423: '용',
  424: '이도',
  425: '삼겹살',
  426: '쿠키',
  427: '센스',
  428: '해지',
  429: '거기',
  430: '시그널',
  431: '가보',
  432: '식당',
  433: '지난',
  434: '순간',
  435: '소고기',
  436: '박준',
  437: '누가',
  438: '와인',
  439: '공간',
  440: '고이',
  441: '신기',
  442: '각하',
  443: '쿠폰',
  444: '첫째',
  445: '만두',
  446: '다이어리',
  447: '어제',
  448: '대신',
  449: '집중',
  450: '다이어트',
  451: '오지',
  452: '가요',
  453: '어찌',
  454: '감기',
  455: '작년',
  456: '장면',
  457: '부분',
  458: '저번',
  459: '연출',
  460: '목요일',
  461: '간장',
  462: '마리',
  463: '피곤',
  464: '둘째',
  465: '커플',
  466: '여보',
  467: '대충',
  468: '중간',
  469: '검색',
  470: '튀김',
  471: '육아',
  472: '카카오페이지',
  473: '기자',
  474: '실내',
  475: '주차',
  476: '볼',
  477: '대박',
  478: '편',
  479: '스벅',
  480: '서도',
  481: '계획',
  482: '그',
  483: '장소',
  484: '만원',
  485: '중',
  486: '나',
  487: '내년',
  488: '그때',
  489: '미니',
  490: '직접',
  491: '한잔',
  492: '조심',
  493: '주시',
  494: '야식',
  495: '공개',
  496: '현실',
  497: '식사',
  498: '물놀이',
  499: '잡고',
  500: '최근',
  501: '모닝',
  502: '국물',
  503: '포인트',
  504: '네이버',
  505: '시영',
  506: '강철',
  507: '애기',
  508: '플레이',
  509: '남아',
  510: '구입',
  511: '외식',
  512: '필수',
  513: '인분',
  514: '일기',
  515: '할인',
  516: '기묘',
  517: '부시',
  518: '미래',
  519: '음으로',
  520: '표정',
  521: '후',
  522: '특별',
  523: '나이',
  524: '말',
  525: '양파',
  526: '이하',
  527: '널',
  528: '시작',
  529: '케이스',
  530: '겨우',
  531: '분',
  532: '안',
  533: '주변',
  534: '인형',
  535: '분명',
  536: '눈',
  537: '리하',
  538: '작업',
  539: '감사',
  540: '시험',
  541: '슈퍼',
  542: '두번째',
  543: '위',
  544: '부부',
  545: '옛날',
  546: '데리',
  547: '난리',
  548: '라거',
  549: '딸기',
  550: '스타',
  551: '주',
  552: '테이블',
  553: '빨래',
  554: '가끔',
  555: '라가',
  556: '차요',
  557: '못',
  558: '방콕',
  559: '어진',
  560: '웨이',
  561: '스트레스',
  562: '귀가',
  563: '미안',
  564: '반복',
  565: '다지',
  566: '펭수',
  567: '여자',
  568: '자신',
  569: '카드',
  570: '밀크',
  571: '니지',
  572: '고고',
  573: '음료',
  574: '초코',
  575: '마취',
  576: '잔뜩',
  577: '루솔',
  578: '인테리어',
  579: '체험',
  580: '서로',
  581: '달달',
  582: '여전',
  583: '보시',
  584: '완료',
  585: '필요',
  586: '그게',
  587: '헤어',
  588: '불편',
  589: '나머지',
  590: '오니',
  591: '맞이',
  592: '제발',
  593: '포기',
  594: '어플',
  595: '운전',
  596: '시',
  597: '아래',
  598: '쿠션',
  599: '조만간',
  600: '기전',
  601: '구시',
  602: '금방',
  603: '청소',
  604: '그것',
  605: '스팀',
  606: '어린이집',
  607: '기고',
  608: '이로',
  609: '알바',
  610: '교수',
  611: '귀걸이',
  612: '크림',
  613: '런가',
  614: '예능',
  615: '천원',
  616: '모양',
  617: '김밥',
  618: '책',
  619: '컨트롤러',
  620: '자체',
  621: '연말',
  622: '위인',
  623: '인천',
  624: '마카롱',
  625: '계란',
  626: '졸업',
  627: '등',
  628: '주기',
  629: '결혼식',
  630: '지게',
  631: '감동',
  632: '다그',
  633: '도전',
  634: '감성',
  635: '최애',
  636: '정보',
  637: '비밀',
  638: '마블',
  639: '다이소',
  640: '할머니',
  641: '누구',
  642: '출산',
  643: '거지',
  644: '상태',
  645: '상황',
  646: '오픈',
  647: '보리',
  648: '사진',
  649: '바퀴',
  650: '데이터',
  651: '구름',
  652: '해장',
  653: '부동산',
  654: '평일',
  655: '요거트',
  656: '배부',
  657: '당신',
  658: '계란찜',
  659: '겨울왕국',
  660: '내부',
  661: '도',
  662: '새우',
  663: '범례',
  664: '힐링',
  665: '그나',
  666: '편의점',
  667: '붕어빵',
  668: '경제',
  669: '점점',
  670: '참고',
  671: '조절',
  672: '결제',
  673: '점심시간',
  674: '순위',
  675: '솔직',
  676: '네일',
  677: '왜',
  678: '목소리',
  679: '치면',
  680: '사건',
  681: '달',
  682: '지랄',
  683: '확인',
  684: '서비스',
  685: '셀카',
  686: '완성',
  687: '조합',
  688: '만하',
  689: '노을',
  690: '블루',
  691: '신경',
  692: '부담',
  693: '고구마',
  694: '도국',
  695: '존재',
  696: '스티커',
  697: '축제',
  698: '에어',
  699: '워낙',
  700: '시기',
  701: '매우',
  702: '인증',
  703: '채널',
  704: '통해',
  705: '연락',
  706: '임신',
  707: '만들기',
  708: '마늘',
  709: '네',
  710: '웃기',
  711: '냉장고',
  712: '창문',
  713: '감정',
  714: '브라운',
  715: '카톡',
  716: '약간',
  717: '기본',
  718: '계절',
  719: '소주',
  720: '고급',
  721: '모임',
  722: '기록',
  723: '폭풍',
  724: '강아지',
  725: '당면',
  726: '둘이서',
  727: '주먹밥',
  728: '백화점',
  729: '린다',
  730: '유기농',
  731: '리스트',
  732: '듯이',
  733: '시드니',
  734: '버터',
  735: '계속',
  736: '감자',
  737: '의미',
  738: '연속',
  739: '만난',
  740: '프로그램',
  741: '때문',
  742: '끼리',
  743: '확실',
  744: '공원',
  745: '수록',
  746: '일어나서',
  747: '대한',
  748: '일정',
  749: '이용',
  750: '고객',
  751: '기술',
  752: '말씀',
  753: '중드',
  754: '슬슬',
  755: '친정',
  756: '차',
  757: '컨디션',
  758: '후기',
  759: '뚝딱',
  760: '본방',
  761: '기준',
  762: '브이',
  763: '집안일',
  764: '위로',
  765: '콘서트',
  766: '새해',
  767: '에어컨',
  768: '토스트',
  769: '학원',
  770: '이틀',
  771: '작성',
  772: '목표',
  773: '막상',
  774: '예고편',
  775: '고양이',
  776: '대해',
  777: '왼쪽',
  778: '또한',
  779: '한참',
  780: '대학생',
  781: '구성',
  782: '등등',
  783: '휴무',
  784: '심지어',
  785: '대상',
  786: '구이',
  787: '소품',
  788: '오른쪽',
  789: '우유',
  790: '의자',
  791: '었는데',
  792: '대구',
  793: '당장',
  794: '시청',
  795: '후다닥',
  796: '액션',
  797: '진심',
  798: '문제',
  799: '다나',
  800: '정화',
  801: '먼지',
  802: '끝내',
  803: '냉동',
  804: '강제',
  805: '사주',
  806: '보관',
  807: '벚꽃',
  808: '지창욱',
  809: '기간',
  810: '차로',
  811: '무대',
  812: '출처',
  813: '주차장',
  814: '듬뿍',
  815: '밴드',
  816: '기하',
  817: '등장',
  818: '그러케',
  819: '김치찌개',
  820: '원피스',
  821: '버섯',
  822: '수도',
  823: '노력',
  824: '핫도그',
  825: '까운',
  826: '브런치',
  827: '잠시',
  828: '그거',
  829: '편이',
  830: '나들이',
  831: '가게',
  832: '이면',
  833: '바닥',
  834: '초밥',
  835: '제주도',
  836: '인물',
  837: '화이팅',
  838: '안해',
  839: '증말',
  840: '달리',
  841: '후회',
  842: '장르',
  843: '코스',
  844: '라이트',
  845: '역시',
  846: '노트북',
  847: '페이',
  848: '돈까스',
  849: '판매',
  850: '시절',
  851: '보라',
  852: '만남',
  853: '도쿄',
  854: '만해',
  855: '체력',
  856: '년전',
  857: '센터',
  858: '파트너',
  859: '불금',
  860: '아지',
  861: '행차',
  862: '성격',
  863: '제주',
  864: '지인',
  865: '안주',
  866: '이기',
  867: '경기도',
  868: '크게',
  869: '피부',
  870: '보지',
  871: '한지',
  872: '닥터',
  873: '안고',
  874: '이자',
  875: '구월동',
  876: '다양',
  877: '하라',
  878: '기름',
  879: '내기',
  880: '노잼',
  881: '궁금',
  882: '닭갈비',
  883: '자연',
  884: '신기하',
  885: '단지',
  886: '장난',
  887: '핑크',
  888: '배송',
  889: '하나',
  890: '보아',
  891: '티켓',
  892: '국내',
  893: '축하',
  894: '판타지',
  895: '포토',
  896: '토욜',
  897: '서울특별시',
  898: '가방',
  899: '미국',
  900: '메인',
  901: '설',
  902: '과제',
  903: '어른',
  904: '어묵',
  905: '부작',
  906: '댓글',
  907: '디즈니',
  908: '부족',
  909: '통닭',
  910: '걸',
  911: '뚝배기',
  912: '고추',
  913: '득템',
  914: '참여',
  915: '위치',
  916: '에버랜드',
  917: '절대',
  918: '색깔',
  919: '무려',
  920: '엽떡',
  921: '종종',
  922: '워홀',
  923: '브랜드',
  924: '려면',
  925: '살이',
  926: '가다가',
  927: '진료',
  928: '가구',
  929: '이전',
  930: '유럽',
  931: '마침',
  932: '오일',
  933: '샐러드',
  934: '투어',
  935: '어마',
  936: '그날',
  937: '얼집',
  938: '나무',
  939: '소화',
  940: '묵향',
  941: '우리동네',
  942: '당일',
  943: '효과',
  944: '보통',
  945: '라이브',
  946: '인터넷',
  947: '행해',
  948: '일차',
  949: '호텔',
  950: '고해',
  951: '다크',
  952: '임산부',
  953: '심장',
  954: '돌이',
  955: '더욱',
  956: '곱창',
  957: '인사',
  958: '지방',
  959: '지면',
  960: '눈치',
  961: '루나',
  962: '현빈',
  963: '취소',
  964: '다운',
  965: '입맛',
  966: '정도',
  967: '등원',
  968: '첫사랑',
  969: '러브',
  970: '더더',
  971: '생기',
  972: '클리어',
  973: '전혀',
  974: '스시',
  975: '기념',
  976: '샤브샤브',
  977: '티켓팅',
  978: '저기',
  979: '데이트',
  980: '선수',
  981: '글',
  982: '구리',
  983: '과거',
  984: '선생님',
  985: '마지막',
  986: '가디건',
  987: '매번',
  988: '형제',
  989: '장전동',
  990: '한편',
  991: '대서',
  992: '결말',
  993: '신세계',
  994: '죽음',
  995: '이웃',
  996: '상우',
  997: '심해',
  998: '최대한',
  999: '사장',
  ...},
 '횟수': {0: 531,
  1: 463,
  2: 447,
  3: 432,
  4: 335,
  5: 321,
  6: 288,
  7: 278,
  8: 262,
  9: 256,
  10: 238,
  11: 229,
  12: 226,
  13: 210,
  14: 202,
  15: 200,
  16: 198,
  17: 196,
  18: 190,
  19: 185,
  20: 183,
  21: 183,
  22: 183,
  23: 181,
  24: 180,
  25: 180,
  26: 174,
  27: 174,
  28: 172,
  29: 168,
  30: 166,
  31: 164,
  32: 164,
  33: 156,
  34: 155,
  35: 154,
  36: 149,
  37: 148,
  38: 144,
  39: 142,
  40: 140,
  41: 139,
  42: 137,
  43: 136,
  44: 133,
  45: 131,
  46: 129,
  47: 129,
  48: 128,
  49: 127,
  50: 127,
  51: 126,
  52: 124,
  53: 124,
  54: 123,
  55: 123,
  56: 122,
  57: 120,
  58: 120,
  59: 120,
  60: 116,
  61: 116,
  62: 116,
  63: 116,
  64: 114,
  65: 114,
  66: 114,
  67: 114,
  68: 113,
  69: 111,
  70: 111,
  71: 110,
  72: 110,
  73: 110,
  74: 109,
  75: 109,
  76: 108,
  77: 108,
  78: 108,
  79: 107,
  80: 107,
  81: 105,
  82: 105,
  83: 103,
  84: 101,
  85: 101,
  86: 100,
  87: 100,
  88: 99,
  89: 99,
  90: 98,
  91: 98,
  92: 97,
  93: 96,
  94: 95,
  95: 95,
  96: 93,
  97: 93,
  98: 93,
  99: 93,
  100: 92,
  101: 92,
  102: 90,
  103: 89,
  104: 89,
  105: 89,
  106: 89,
  107: 88,
  108: 87,
  109: 87,
  110: 86,
  111: 86,
  112: 86,
  113: 85,
  114: 85,
  115: 85,
  116: 85,
  117: 83,
  118: 83,
  119: 82,
  120: 82,
  121: 82,
  122: 81,
  123: 81,
  124: 81,
  125: 80,
  126: 80,
  127: 80,
  128: 80,
  129: 80,
  130: 79,
  131: 79,
  132: 78,
  133: 78,
  134: 78,
  135: 78,
  136: 78,
  137: 78,
  138: 78,
  139: 78,
  140: 77,
  141: 77,
  142: 77,
  143: 76,
  144: 76,
  145: 76,
  146: 76,
  147: 76,
  148: 76,
  149: 75,
  150: 74,
  151: 74,
  152: 73,
  153: 73,
  154: 73,
  155: 72,
  156: 72,
  157: 72,
  158: 71,
  159: 71,
  160: 71,
  161: 71,
  162: 70,
  163: 70,
  164: 70,
  165: 70,
  166: 68,
  167: 68,
  168: 68,
  169: 68,
  170: 68,
  171: 68,
  172: 68,
  173: 68,
  174: 67,
  175: 67,
  176: 67,
  177: 67,
  178: 66,
  179: 66,
  180: 66,
  181: 65,
  182: 65,
  183: 65,
  184: 65,
  185: 65,
  186: 65,
  187: 64,
  188: 64,
  189: 64,
  190: 64,
  191: 64,
  192: 64,
  193: 63,
  194: 63,
  195: 63,
  196: 63,
  197: 62,
  198: 62,
  199: 62,
  200: 62,
  201: 62,
  202: 61,
  203: 61,
  204: 61,
  205: 61,
  206: 61,
  207: 61,
  208: 61,
  209: 60,
  210: 60,
  211: 60,
  212: 60,
  213: 60,
  214: 60,
  215: 60,
  216: 60,
  217: 60,
  218: 60,
  219: 60,
  220: 60,
  221: 60,
  222: 60,
  223: 60,
  224: 60,
  225: 60,
  226: 60,
  227: 60,
  228: 59,
  229: 59,
  230: 59,
  231: 59,
  232: 59,
  233: 58,
  234: 58,
  235: 58,
  236: 58,
  237: 58,
  238: 58,
  239: 57,
  240: 57,
  241: 57,
  242: 57,
  243: 57,
  244: 57,
  245: 57,
  246: 56,
  247: 56,
  248: 56,
  249: 56,
  250: 56,
  251: 55,
  252: 55,
  253: 55,
  254: 55,
  255: 55,
  256: 55,
  257: 55,
  258: 55,
  259: 54,
  260: 54,
  261: 54,
  262: 54,
  263: 54,
  264: 54,
  265: 54,
  266: 54,
  267: 54,
  268: 53,
  269: 53,
  270: 53,
  271: 53,
  272: 53,
  273: 53,
  274: 53,
  275: 53,
  276: 52,
  277: 52,
  278: 52,
  279: 52,
  280: 52,
  281: 52,
  282: 52,
  283: 52,
  284: 52,
  285: 51,
  286: 51,
  287: 51,
  288: 51,
  289: 51,
  290: 51,
  291: 51,
  292: 51,
  293: 51,
  294: 50,
  295: 50,
  296: 50,
  297: 50,
  298: 50,
  299: 50,
  300: 50,
  301: 50,
  302: 49,
  303: 49,
  304: 49,
  305: 49,
  306: 49,
  307: 49,
  308: 49,
  309: 49,
  310: 49,
  311: 48,
  312: 48,
  313: 48,
  314: 48,
  315: 47,
  316: 47,
  317: 47,
  318: 47,
  319: 47,
  320: 47,
  321: 46,
  322: 46,
  323: 46,
  324: 46,
  325: 46,
  326: 46,
  327: 46,
  328: 46,
  329: 46,
  330: 46,
  331: 46,
  332: 46,
  333: 46,
  334: 45,
  335: 45,
  336: 45,
  337: 45,
  338: 45,
  339: 45,
  340: 45,
  341: 45,
  342: 45,
  343: 45,
  344: 45,
  345: 45,
  346: 45,
  347: 44,
  348: 44,
  349: 44,
  350: 44,
  351: 44,
  352: 44,
  353: 44,
  354: 44,
  355: 44,
  356: 44,
  357: 44,
  358: 44,
  359: 44,
  360: 43,
  361: 43,
  362: 43,
  363: 43,
  364: 43,
  365: 43,
  366: 43,
  367: 43,
  368: 43,
  369: 43,
  370: 43,
  371: 42,
  372: 42,
  373: 42,
  374: 42,
  375: 42,
  376: 42,
  377: 42,
  378: 42,
  379: 42,
  380: 42,
  381: 42,
  382: 42,
  383: 42,
  384: 42,
  385: 42,
  386: 42,
  387: 42,
  388: 42,
  389: 42,
  390: 41,
  391: 41,
  392: 41,
  393: 41,
  394: 41,
  395: 41,
  396: 41,
  397: 41,
  398: 41,
  399: 41,
  400: 40,
  401: 40,
  402: 40,
  403: 40,
  404: 40,
  405: 40,
  406: 40,
  407: 40,
  408: 40,
  409: 40,
  410: 40,
  411: 40,
  412: 40,
  413: 40,
  414: 40,
  415: 40,
  416: 40,
  417: 39,
  418: 39,
  419: 39,
  420: 39,
  421: 39,
  422: 39,
  423: 39,
  424: 39,
  425: 39,
  426: 39,
  427: 39,
  428: 39,
  429: 39,
  430: 38,
  431: 38,
  432: 38,
  433: 38,
  434: 38,
  435: 38,
  436: 38,
  437: 38,
  438: 38,
  439: 38,
  440: 38,
  441: 38,
  442: 38,
  443: 37,
  444: 37,
  445: 37,
  446: 37,
  447: 37,
  448: 37,
  449: 37,
  450: 37,
  451: 37,
  452: 37,
  453: 37,
  454: 37,
  455: 37,
  456: 37,
  457: 37,
  458: 37,
  459: 37,
  460: 36,
  461: 36,
  462: 36,
  463: 36,
  464: 36,
  465: 36,
  466: 36,
  467: 36,
  468: 36,
  469: 36,
  470: 36,
  471: 35,
  472: 35,
  473: 35,
  474: 35,
  475: 35,
  476: 35,
  477: 35,
  478: 35,
  479: 35,
  480: 35,
  481: 35,
  482: 35,
  483: 35,
  484: 35,
  485: 35,
  486: 35,
  487: 35,
  488: 35,
  489: 35,
  490: 35,
  491: 35,
  492: 35,
  493: 34,
  494: 34,
  495: 34,
  496: 34,
  497: 34,
  498: 34,
  499: 34,
  500: 34,
  501: 34,
  502: 34,
  503: 34,
  504: 34,
  505: 34,
  506: 34,
  507: 34,
  508: 34,
  509: 34,
  510: 34,
  511: 34,
  512: 34,
  513: 34,
  514: 34,
  515: 34,
  516: 34,
  517: 34,
  518: 34,
  519: 34,
  520: 34,
  521: 34,
  522: 34,
  523: 33,
  524: 33,
  525: 33,
  526: 33,
  527: 33,
  528: 33,
  529: 33,
  530: 33,
  531: 33,
  532: 33,
  533: 33,
  534: 33,
  535: 33,
  536: 33,
  537: 33,
  538: 33,
  539: 33,
  540: 32,
  541: 32,
  542: 32,
  543: 32,
  544: 32,
  545: 32,
  546: 32,
  547: 32,
  548: 32,
  549: 32,
  550: 32,
  551: 32,
  552: 32,
  553: 32,
  554: 32,
  555: 32,
  556: 32,
  557: 32,
  558: 32,
  559: 32,
  560: 32,
  561: 32,
  562: 32,
  563: 32,
  564: 32,
  565: 32,
  566: 32,
  567: 32,
  568: 32,
  569: 32,
  570: 32,
  571: 32,
  572: 32,
  573: 32,
  574: 32,
  575: 32,
  576: 32,
  577: 32,
  578: 31,
  579: 31,
  580: 31,
  581: 31,
  582: 31,
  583: 31,
  584: 31,
  585: 31,
  586: 31,
  587: 31,
  588: 31,
  589: 31,
  590: 31,
  591: 31,
  592: 31,
  593: 31,
  594: 31,
  595: 31,
  596: 31,
  597: 31,
  598: 31,
  599: 31,
  600: 31,
  601: 30,
  602: 30,
  603: 30,
  604: 30,
  605: 30,
  606: 30,
  607: 30,
  608: 30,
  609: 30,
  610: 30,
  611: 30,
  612: 30,
  613: 30,
  614: 30,
  615: 30,
  616: 30,
  617: 30,
  618: 30,
  619: 30,
  620: 30,
  621: 30,
  622: 30,
  623: 30,
  624: 30,
  625: 30,
  626: 30,
  627: 30,
  628: 30,
  629: 30,
  630: 30,
  631: 30,
  632: 30,

In [92]:
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import random
img_path = 'c:/py_data/TV.jpg'
cloud_mask = np.array(Image.open(img_path))


wordcloud = WordCloud(font_path="c:/Windows/Fonts/malgun.ttf", 
                      colormap='OrRd',
                      background_color="white", mask=cloud_mask)
wc = wordcloud.generate_from_frequencies(before_cloud)
plt.figure(figsize=(30,40))
plt.imshow(wc)
plt.imshow(wc, interpolation='bilinear')
plt.axis("off")
plt.show()

TypeError: '<' not supported between instances of 'dict' and 'dict'